/gate/world/daughters/name Awedge0
/gate/world/daughters/insert wedge
/gate/Awedge0/geometry/setNarrowerXLength 1e-05 mm
/gate/Awedge0/geometry/setXLength 0.00439901 mm
/gate/Awedge0/geometry/setYLength 0.270533 mm 
/gate/Awedge0/geometry/setZLength 32 mm
/gate/Awedge0/setMaterial Aluminium
/gate/Awedge0/vis/setColor gray
/gate/Awedge0/placement/setTranslation 0.135267 585.001 0 mm
/gate/Awedge0/placement/setRotationAxis -1 1 0
/gate/Awedge0/placement/setRotationAngle 180 deg
/gate/world/daughters/name Awedge1
/gate/world/daughters/insert wedge
/gate/Awedge1/geometry/setNarrowerXLength 0.00439901 mm
/gate/Awedge1/geometry/setXLength 0.00879873 mm
/gate/Awedge1/geometry/setYLength 0.270578 mm 
/gate/Awedge1/geometry/setZLength 32 mm
/gate/Awedge1/setMaterial Aluminium
/gate/Awedge1/vis/setColor gray
/gate/Awedge1/placement/setTranslation 0.405822 585.003 0 mm
/gate/Awedge1/placement/setRotationAxis -1 1 0
/gate/Awedge1/placement/setRotationAngle 180 deg
/gate/world/daughters/name Awedge2
/gate/world/daughters/insert wedge
/gate/Awedge2/geometry/setNarrowerXLength 0.00879873 mm
/gate/Awedge2/geometry/setXLength 0.0131999 mm
/gate/Awedge2/geometry/setYLength 0.270666 mm 
/gate/Awedge2/geometry/setZLength 32 mm
/gate/Awedge2/setMaterial Aluminium
/gate/Awedge2/vis/setColor gray
/gate/Awedge2/placement/setTranslation 0.676444 585.005 0 mm
/gate/Awedge2/placement/setRotationAxis -1 1 0
/gate/Awedge2/placement/setRotationAngle 180 deg
/gate/world/daughters/name Awedge3
/gate/world/daughters/insert wedge
/gate/Awedge3/geometry/setNarrowerXLength 0.0131999 mm
/gate/Awedge3/geometry/setXLength 0.0176032 mm
/gate/Awedge3/geometry/setYLength 0.270799 mm 
/gate/Awedge3/geometry/setZLength 32 mm
/gate/Awedge3/setMaterial Aluminium
/gate/Awedge3/vis/setColor gray
/gate/Awedge3/placement/setTranslation 0.947176 585.008 0 mm
/gate/Awedge3/placement/setRotationAxis -1 1 0
/gate/Awedge3/placement/setRotationAngle 180 deg
/gate/world/daughters/name Awedge4
/gate/world/daughters/insert wedge
/gate/Awedge4/geometry/setNarrowerXLength 0.0176032 mm
/gate/Awedge4/geometry/setXLength 0.0220094 mm
/gate/Awedge4/geometry/setYLength 0.270976 mm 
/gate/Awedge4/geometry/setZLength 32 mm
/gate/Awedge4/setMaterial Aluminium
/gate/Awedge4/vis/setColor gray
/gate/Awedge4/placement/setTranslation 1.21806 585.01 0 mm
/gate/Awedge4/placement/setRotationAxis -1 1 0
/gate/Awedge4/placement/setRotationAngle 180 deg
/gate/world/daughters/name Awedge5
/gate/world/daughters/insert wedge
/gate/Awedge5/geometry/setNarrowerXLength 0.0220094 mm
/gate/Awedge5/geometry/setXLength 0.0264192 mm
/gate/Awedge5/geometry/setYLength 0.271197 mm 
/gate/Awedge5/geometry/setZLength 32 mm
/gate/Awedge5/setMaterial Aluminium
/gate/Awedge5/vis/setColor gray
/gate/Awedge5/placement/setTranslation 1.48915 585.012 0 mm
/gate/Awedge5/placement/setRotationAxis -1 1 0
/gate/Awedge5/placement/setRotationAngle 180 deg
/gate/world/daughters/name Awedge6
/gate/world/daughters/insert wedge
/gate/Awedge6/geometry/setNarrowerXLength 0.0264192 mm
/gate/Awedge6/geometry/setXLength 0.0308334 mm
/gate/Awedge6/geometry/setYLength 0.271463 mm 
/gate/Awedge6/geometry/setZLength 32 mm
/gate/Awedge6/setMaterial Aluminium
/gate/Awedge6/vis/setColor gray
/gate/Awedge6/placement/setTranslation 1.76048 585.014 0 mm
/gate/Awedge6/placement/setRotationAxis -1 1 0
/gate/Awedge6/placement/setRotationAngle 180 deg
/gate/world/daughters/name Awedge7
/gate/world/daughters/insert wedge
/gate/Awedge7/geometry/setNarrowerXLength 0.0308334 mm
/gate/Awedge7/geometry/setXLength 0.0352525 mm
/gate/Awedge7/geometry/setYLength 0.271774 mm 
/gate/Awedge7/geometry/setZLength 32 mm
/gate/Awedge7/setMaterial Aluminium
/gate/Awedge7/vis/setColor gray
/gate/Awedge7/placement/setTranslation 2.0321 585.017 0 mm
/gate/Awedge7/placement/setRotationAxis -1 1 0
/gate/Awedge7/placement/setRotationAngle 180 deg
/gate/world/daughters/name Awedge8
/gate/world/daughters/insert wedge
/gate/Awedge8/geometry/setNarrowerXLength 0.0352525 mm
/gate/Awedge8/geometry/setXLength 0.0396775 mm
/gate/Awedge8/geometry/setYLength 0.27213 mm 
/gate/Awedge8/geometry/setZLength 32 mm
/gate/Awedge8/setMaterial Aluminium
/gate/Awedge8/vis/setColor gray
/gate/Awedge8/placement/setTranslation 2.30405 585.019 0 mm
/gate/Awedge8/placement/setRotationAxis -1 1 0
/gate/Awedge8/placement/setRotationAngle 180 deg
/gate/world/daughters/name Awedge9
/gate/world/daughters/insert wedge
/gate/Awedge9/geometry/setNarrowerXLength 0.0396775 mm
/gate/Awedge9/geometry/setXLength 0.044109 mm
/gate/Awedge9/geometry/setYLength 0.272531 mm 
/gate/Awedge9/geometry/setZLength 32 mm
/gate/Awedge9/setMaterial Aluminium
/gate/Awedge9/vis/setColor gray
/gate/Awedge9/placement/setTranslation 2.57638 585.021 0 mm
/gate/Awedge9/placement/setRotationAxis -1 1 0
/gate/Awedge9/placement/setRotationAngle 180 deg
/gate/world/daughters/name Awedge10
/gate/world/daughters/insert wedge
/gate/Awedge10/geometry/setNarrowerXLength 0.044109 mm
/gate/Awedge10/geometry/setXLength 0.0485478 mm
/gate/Awedge10/geometry/setYLength 0.272977 mm 
/gate/Awedge10/geometry/setZLength 32 mm
/gate/Awedge10/setMaterial Aluminium
/gate/Awedge10/vis/setColor gray
/gate/Awedge10/placement/setTranslation 2.84914 585.023 0 mm
/gate/Awedge10/placement/setRotationAxis -1 1 0
/gate/Awedge10/placement/setRotationAngle 180 deg
/gate/world/daughters/name Awedge11
/gate/world/daughters/insert wedge
/gate/Awedge11/geometry/setNarrowerXLength 0.0485478 mm
/gate/Awedge11/geometry/setXLength 0.0529945 mm
/gate/Awedge11/geometry/setYLength 0.273469 mm 
/gate/Awedge11/geometry/setZLength 32 mm
/gate/Awedge11/setMaterial Aluminium
/gate/Awedge11/vis/setColor gray
/gate/Awedge11/placement/setTranslation 3.12236 585.025 0 mm
/gate/Awedge11/placement/setRotationAxis -1 1 0
/gate/Awedge11/placement/setRotationAngle 180 deg
/gate/world/daughters/name Awedge12
/gate/world/daughters/insert wedge
/gate/Awedge12/geometry/setNarrowerXLength 0.0529945 mm
/gate/Awedge12/geometry/setXLength 0.05745 mm
/gate/Awedge12/geometry/setYLength 0.274007 mm 
/gate/Awedge12/geometry/setZLength 32 mm
/gate/Awedge12/setMaterial Aluminium
/gate/Awedge12/vis/setColor gray
/gate/Awedge12/placement/setTranslation 3.3961 585.028 0 mm
/gate/Awedge12/placement/setRotationAxis -1 1 0
/gate/Awedge12/placement/setRotationAngle 180 deg
/gate/world/daughters/name Awedge13
/gate/world/daughters/insert wedge
/gate/Awedge13/geometry/setNarrowerXLength 0.05745 mm
/gate/Awedge13/geometry/setXLength 0.061915 mm
/gate/Awedge13/geometry/setYLength 0.274592 mm 
/gate/Awedge13/geometry/setZLength 32 mm
/gate/Awedge13/setMaterial Aluminium
/gate/Awedge13/vis/setColor gray
/gate/Awedge13/placement/setTranslation 3.6704 585.03 0 mm
/gate/Awedge13/placement/setRotationAxis -1 1 0
/gate/Awedge13/placement/setRotationAngle 180 deg
/gate/world/daughters/name Awedge14
/gate/world/daughters/insert wedge
/gate/Awedge14/geometry/setNarrowerXLength 0.061915 mm
/gate/Awedge14/geometry/setXLength 0.0663903 mm
/gate/Awedge14/geometry/setYLength 0.275223 mm 
/gate/Awedge14/geometry/setZLength 32 mm
/gate/Awedge14/setMaterial Aluminium
/gate/Awedge14/vis/setColor gray
/gate/Awedge14/placement/setTranslation 3.9453 585.032 0 mm
/gate/Awedge14/placement/setRotationAxis -1 1 0
/gate/Awedge14/placement/setRotationAngle 180 deg
/gate/world/daughters/name Awedge15
/gate/world/daughters/insert wedge
/gate/Awedge15/geometry/setNarrowerXLength 0.0663903 mm
/gate/Awedge15/geometry/setXLength 0.0708765 mm
/gate/Awedge15/geometry/setYLength 0.275901 mm 
/gate/Awedge15/geometry/setZLength 32 mm
/gate/Awedge15/setMaterial Aluminium
/gate/Awedge15/vis/setColor gray
/gate/Awedge15/placement/setTranslation 4.22087 585.034 0 mm
/gate/Awedge15/placement/setRotationAxis -1 1 0
/gate/Awedge15/placement/setRotationAngle 180 deg
/gate/world/daughters/name Awedge16
/gate/world/daughters/insert wedge
/gate/Awedge16/geometry/setNarrowerXLength 0.0708765 mm
/gate/Awedge16/geometry/setXLength 0.0753746 mm
/gate/Awedge16/geometry/setYLength 0.276626 mm 
/gate/Awedge16/geometry/setZLength 32 mm
/gate/Awedge16/setMaterial Aluminium
/gate/Awedge16/vis/setColor gray
/gate/Awedge16/placement/setTranslation 4.49713 585.037 0 mm
/gate/Awedge16/placement/setRotationAxis -1 1 0
/gate/Awedge16/placement/setRotationAngle 180 deg
/gate/world/daughters/name Awedge17
/gate/world/daughters/insert wedge
/gate/Awedge17/geometry/setNarrowerXLength 0.0753746 mm
/gate/Awedge17/geometry/setXLength 0.0798853 mm
/gate/Awedge17/geometry/setYLength 0.277399 mm 
/gate/Awedge17/geometry/setZLength 32 mm
/gate/Awedge17/setMaterial Aluminium
/gate/Awedge17/vis/setColor gray
/gate/Awedge17/placement/setTranslation 4.77414 585.039 0 mm
/gate/Awedge17/placement/setRotationAxis -1 1 0
/gate/Awedge17/placement/setRotationAngle 180 deg
/gate/world/daughters/name Awedge18
/gate/world/daughters/insert wedge
/gate/Awedge18/geometry/setNarrowerXLength 0.0798853 mm
/gate/Awedge18/geometry/setXLength 0.0844093 mm
/gate/Awedge18/geometry/setYLength 0.278221 mm 
/gate/Awedge18/geometry/setZLength 32 mm
/gate/Awedge18/setMaterial Aluminium
/gate/Awedge18/vis/setColor gray
/gate/Awedge18/placement/setTranslation 5.05195 585.041 0 mm
/gate/Awedge18/placement/setRotationAxis -1 1 0
/gate/Awedge18/placement/setRotationAngle 180 deg
/gate/world/daughters/name Awedge19
/gate/world/daughters/insert wedge
/gate/Awedge19/geometry/setNarrowerXLength 0.0844093 mm
/gate/Awedge19/geometry/setXLength 0.0889474 mm
/gate/Awedge19/geometry/setYLength 0.279091 mm 
/gate/Awedge19/geometry/setZLength 32 mm
/gate/Awedge19/setMaterial Aluminium
/gate/Awedge19/vis/setColor gray
/gate/Awedge19/placement/setTranslation 5.33061 585.043 0 mm
/gate/Awedge19/placement/setRotationAxis -1 1 0
/gate/Awedge19/placement/setRotationAngle 180 deg
/gate/world/daughters/name Awedge20
/gate/world/daughters/insert wedge
/gate/Awedge20/geometry/setNarrowerXLength 0.0889474 mm
/gate/Awedge20/geometry/setXLength 0.0935006 mm
/gate/Awedge20/geometry/setYLength 0.280011 mm 
/gate/Awedge20/geometry/setZLength 32 mm
/gate/Awedge20/setMaterial Aluminium
/gate/Awedge20/vis/setColor gray
/gate/Awedge20/placement/setTranslation 5.61016 585.046 0 mm
/gate/Awedge20/placement/setRotationAxis -1 1 0
/gate/Awedge20/placement/setRotationAngle 180 deg
/gate/world/daughters/name Awedge21
/gate/world/daughters/insert wedge
/gate/Awedge21/geometry/setNarrowerXLength 0.0935006 mm
/gate/Awedge21/geometry/setXLength 0.0980694 mm
/gate/Awedge21/geometry/setYLength 0.280981 mm 
/gate/Awedge21/geometry/setZLength 32 mm
/gate/Awedge21/setMaterial Aluminium
/gate/Awedge21/vis/setColor gray
/gate/Awedge21/placement/setTranslation 5.89065 585.048 0 mm
/gate/Awedge21/placement/setRotationAxis -1 1 0
/gate/Awedge21/placement/setRotationAngle 180 deg
/gate/world/daughters/name Awedge22
/gate/world/daughters/insert wedge
/gate/Awedge22/geometry/setNarrowerXLength 0.0980694 mm
/gate/Awedge22/geometry/setXLength 0.102655 mm
/gate/Awedge22/geometry/setYLength 0.282001 mm 
/gate/Awedge22/geometry/setZLength 32 mm
/gate/Awedge22/setMaterial Aluminium
/gate/Awedge22/vis/setColor gray
/gate/Awedge22/placement/setTranslation 6.17215 585.05 0 mm
/gate/Awedge22/placement/setRotationAxis -1 1 0
/gate/Awedge22/placement/setRotationAngle 180 deg
/gate/world/daughters/name Awedge23
/gate/world/daughters/insert wedge
/gate/Awedge23/geometry/setNarrowerXLength 0.102655 mm
/gate/Awedge23/geometry/setXLength 0.107258 mm
/gate/Awedge23/geometry/setYLength 0.283073 mm 
/gate/Awedge23/geometry/setZLength 32 mm
/gate/Awedge23/setMaterial Aluminium
/gate/Awedge23/vis/setColor gray
/gate/Awedge23/placement/setTranslation 6.45468 585.052 0 mm
/gate/Awedge23/placement/setRotationAxis -1 1 0
/gate/Awedge23/placement/setRotationAngle 180 deg
/gate/world/daughters/name Awedge24
/gate/world/daughters/insert wedge
/gate/Awedge24/geometry/setNarrowerXLength 0.107258 mm
/gate/Awedge24/geometry/setXLength 0.111879 mm
/gate/Awedge24/geometry/setYLength 0.284197 mm 
/gate/Awedge24/geometry/setZLength 32 mm
/gate/Awedge24/setMaterial Aluminium
/gate/Awedge24/vis/setColor gray
/gate/Awedge24/placement/setTranslation 6.73832 585.055 0 mm
/gate/Awedge24/placement/setRotationAxis -1 1 0
/gate/Awedge24/placement/setRotationAngle 180 deg
/gate/world/daughters/name Awedge25
/gate/world/daughters/insert wedge
/gate/Awedge25/geometry/setNarrowerXLength 0.111879 mm
/gate/Awedge25/geometry/setXLength 0.116519 mm
/gate/Awedge25/geometry/setYLength 0.285373 mm 
/gate/Awedge25/geometry/setZLength 32 mm
/gate/Awedge25/setMaterial Aluminium
/gate/Awedge25/vis/setColor gray
/gate/Awedge25/placement/setTranslation 7.0231 585.057 0 mm
/gate/Awedge25/placement/setRotationAxis -1 1 0
/gate/Awedge25/placement/setRotationAngle 180 deg
/gate/world/daughters/name Awedge26
/gate/world/daughters/insert wedge
/gate/Awedge26/geometry/setNarrowerXLength 0.116519 mm
/gate/Awedge26/geometry/setXLength 0.12118 mm
/gate/Awedge26/geometry/setYLength 0.286603 mm 
/gate/Awedge26/geometry/setZLength 32 mm
/gate/Awedge26/setMaterial Aluminium
/gate/Awedge26/vis/setColor gray
/gate/Awedge26/placement/setTranslation 7.30909 585.059 0 mm
/gate/Awedge26/placement/setRotationAxis -1 1 0
/gate/Awedge26/placement/setRotationAngle 180 deg
/gate/world/daughters/name Awedge27
/gate/world/daughters/insert wedge
/gate/Awedge27/geometry/setNarrowerXLength 0.12118 mm
/gate/Awedge27/geometry/setXLength 0.125861 mm
/gate/Awedge27/geometry/setYLength 0.287888 mm 
/gate/Awedge27/geometry/setZLength 32 mm
/gate/Awedge27/setMaterial Aluminium
/gate/Awedge27/vis/setColor gray
/gate/Awedge27/placement/setTranslation 7.59634 585.062 0 mm
/gate/Awedge27/placement/setRotationAxis -1 1 0
/gate/Awedge27/placement/setRotationAngle 180 deg
/gate/world/daughters/name Awedge28
/gate/world/daughters/insert wedge
/gate/Awedge28/geometry/setNarrowerXLength 0.125861 mm
/gate/Awedge28/geometry/setXLength 0.130564 mm
/gate/Awedge28/geometry/setYLength 0.289227 mm 
/gate/Awedge28/geometry/setZLength 32 mm
/gate/Awedge28/setMaterial Aluminium
/gate/Awedge28/vis/setColor gray
/gate/Awedge28/placement/setTranslation 7.88489 585.064 0 mm
/gate/Awedge28/placement/setRotationAxis -1 1 0
/gate/Awedge28/placement/setRotationAngle 180 deg
/gate/world/daughters/name Awedge29
/gate/world/daughters/insert wedge
/gate/Awedge29/geometry/setNarrowerXLength 0.130564 mm
/gate/Awedge29/geometry/setXLength 0.13529 mm
/gate/Awedge29/geometry/setYLength 0.290624 mm 
/gate/Awedge29/geometry/setZLength 32 mm
/gate/Awedge29/setMaterial Aluminium
/gate/Awedge29/vis/setColor gray
/gate/Awedge29/placement/setTranslation 8.17482 585.066 0 mm
/gate/Awedge29/placement/setRotationAxis -1 1 0
/gate/Awedge29/placement/setRotationAngle 180 deg
/gate/world/daughters/name Awedge30
/gate/world/daughters/insert wedge
/gate/Awedge30/geometry/setNarrowerXLength 0.13529 mm
/gate/Awedge30/geometry/setXLength 0.140039 mm
/gate/Awedge30/geometry/setYLength 0.292077 mm 
/gate/Awedge30/geometry/setZLength 32 mm
/gate/Awedge30/setMaterial Aluminium
/gate/Awedge30/vis/setColor gray
/gate/Awedge30/placement/setTranslation 8.46617 585.069 0 mm
/gate/Awedge30/placement/setRotationAxis -1 1 0
/gate/Awedge30/placement/setRotationAngle 180 deg
/gate/world/daughters/name Awedge31
/gate/world/daughters/insert wedge
/gate/Awedge31/geometry/setNarrowerXLength 0.140039 mm
/gate/Awedge31/geometry/setXLength 0.144813 mm
/gate/Awedge31/geometry/setYLength 0.29359 mm 
/gate/Awedge31/geometry/setZLength 32 mm
/gate/Awedge31/setMaterial Aluminium
/gate/Awedge31/vis/setColor gray
/gate/Awedge31/placement/setTranslation 8.759 585.071 0 mm
/gate/Awedge31/placement/setRotationAxis -1 1 0
/gate/Awedge31/placement/setRotationAngle 180 deg
/gate/world/daughters/name Awedge32
/gate/world/daughters/insert wedge
/gate/Awedge32/geometry/setNarrowerXLength 0.144813 mm
/gate/Awedge32/geometry/setXLength 0.149612 mm
/gate/Awedge32/geometry/setYLength 0.295163 mm 
/gate/Awedge32/geometry/setZLength 32 mm
/gate/Awedge32/setMaterial Aluminium
/gate/Awedge32/vis/setColor gray
/gate/Awedge32/placement/setTranslation 9.05338 585.074 0 mm
/gate/Awedge32/placement/setRotationAxis -1 1 0
/gate/Awedge32/placement/setRotationAngle 180 deg
/gate/world/daughters/name Awedge33
/gate/world/daughters/insert wedge
/gate/Awedge33/geometry/setNarrowerXLength 0.149612 mm
/gate/Awedge33/geometry/setXLength 0.154438 mm
/gate/Awedge33/geometry/setYLength 0.296797 mm 
/gate/Awedge33/geometry/setZLength 32 mm
/gate/Awedge33/setMaterial Aluminium
/gate/Awedge33/vis/setColor gray
/gate/Awedge33/placement/setTranslation 9.34936 585.076 0 mm
/gate/Awedge33/placement/setRotationAxis -1 1 0
/gate/Awedge33/placement/setRotationAngle 180 deg
/gate/world/daughters/name Awedge34
/gate/world/daughters/insert wedge
/gate/Awedge34/geometry/setNarrowerXLength 0.154438 mm
/gate/Awedge34/geometry/setXLength 0.159292 mm
/gate/Awedge34/geometry/setYLength 0.298495 mm 
/gate/Awedge34/geometry/setZLength 32 mm
/gate/Awedge34/setMaterial Aluminium
/gate/Awedge34/vis/setColor gray
/gate/Awedge34/placement/setTranslation 9.64701 585.078 0 mm
/gate/Awedge34/placement/setRotationAxis -1 1 0
/gate/Awedge34/placement/setRotationAngle 180 deg
/gate/world/daughters/name Awedge35
/gate/world/daughters/insert wedge
/gate/Awedge35/geometry/setNarrowerXLength 0.159292 mm
/gate/Awedge35/geometry/setXLength 0.164174 mm
/gate/Awedge35/geometry/setYLength 0.300259 mm 
/gate/Awedge35/geometry/setZLength 32 mm
/gate/Awedge35/setMaterial Aluminium
/gate/Awedge35/vis/setColor gray
/gate/Awedge35/placement/setTranslation 9.94638 585.081 0 mm
/gate/Awedge35/placement/setRotationAxis -1 1 0
/gate/Awedge35/placement/setRotationAngle 180 deg
/gate/world/daughters/name Awedge36
/gate/world/daughters/insert wedge
/gate/Awedge36/geometry/setNarrowerXLength 0.164174 mm
/gate/Awedge36/geometry/setXLength 0.169086 mm
/gate/Awedge36/geometry/setYLength 0.30209 mm 
/gate/Awedge36/geometry/setZLength 32 mm
/gate/Awedge36/setMaterial Aluminium
/gate/Awedge36/vis/setColor gray
/gate/Awedge36/placement/setTranslation 10.2476 585.083 0 mm
/gate/Awedge36/placement/setRotationAxis -1 1 0
/gate/Awedge36/placement/setRotationAngle 180 deg
/gate/world/daughters/name Awedge37
/gate/world/daughters/insert wedge
/gate/Awedge37/geometry/setNarrowerXLength 0.169086 mm
/gate/Awedge37/geometry/setXLength 0.17403 mm
/gate/Awedge37/geometry/setYLength 0.303992 mm 
/gate/Awedge37/geometry/setZLength 32 mm
/gate/Awedge37/setMaterial Aluminium
/gate/Awedge37/vis/setColor gray
/gate/Awedge37/placement/setTranslation 10.5506 585.086 0 mm
/gate/Awedge37/placement/setRotationAxis -1 1 0
/gate/Awedge37/placement/setRotationAngle 180 deg
/gate/world/daughters/name Awedge38
/gate/world/daughters/insert wedge
/gate/Awedge38/geometry/setNarrowerXLength 0.17403 mm
/gate/Awedge38/geometry/setXLength 0.179005 mm
/gate/Awedge38/geometry/setYLength 0.305968 mm 
/gate/Awedge38/geometry/setZLength 32 mm
/gate/Awedge38/setMaterial Aluminium
/gate/Awedge38/vis/setColor gray
/gate/Awedge38/placement/setTranslation 10.8556 585.088 0 mm
/gate/Awedge38/placement/setRotationAxis -1 1 0
/gate/Awedge38/placement/setRotationAngle 180 deg
/gate/world/daughters/name Awedge39
/gate/world/daughters/insert wedge
/gate/Awedge39/geometry/setNarrowerXLength 0.179005 mm
/gate/Awedge39/geometry/setXLength 0.184013 mm
/gate/Awedge39/geometry/setYLength 0.30802 mm 
/gate/Awedge39/geometry/setZLength 32 mm
/gate/Awedge39/setMaterial Aluminium
/gate/Awedge39/vis/setColor gray
/gate/Awedge39/placement/setTranslation 11.1626 585.091 0 mm
/gate/Awedge39/placement/setRotationAxis -1 1 0
/gate/Awedge39/placement/setRotationAngle 180 deg
/gate/world/daughters/name Awedge40
/gate/world/daughters/insert wedge
/gate/Awedge40/geometry/setNarrowerXLength 0.184013 mm
/gate/Awedge40/geometry/setXLength 0.194137 mm
/gate/Awedge40/geometry/setYLength 0.310153 mm 
/gate/Awedge40/geometry/setZLength 32 mm
/gate/Awedge40/setMaterial Aluminium
/gate/Awedge40/vis/setColor gray
/gate/Awedge40/placement/setTranslation 11.4717 585.095 0 mm
/gate/Awedge40/placement/setRotationAxis -1 1 0
/gate/Awedge40/placement/setRotationAngle 180 deg
/gate/world/daughters/name Awedge41
/gate/world/daughters/insert wedge
/gate/Awedge41/geometry/setNarrowerXLength 0.194137 mm
/gate/Awedge41/geometry/setXLength 0.204781 mm
/gate/Awedge41/geometry/setYLength 0.312372 mm 
/gate/Awedge41/geometry/setZLength 32 mm
/gate/Awedge41/setMaterial Aluminium
/gate/Awedge41/vis/setColor gray
/gate/Awedge41/placement/setTranslation 11.7829 585.1 0 mm
/gate/Awedge41/placement/setRotationAxis -1 1 0
/gate/Awedge41/placement/setRotationAngle 180 deg
/gate/world/daughters/name Awedge42
/gate/world/daughters/insert wedge
/gate/Awedge42/geometry/setNarrowerXLength 0.204781 mm
/gate/Awedge42/geometry/setXLength 0.216017 mm
/gate/Awedge42/geometry/setYLength 0.314682 mm 
/gate/Awedge42/geometry/setZLength 32 mm
/gate/Awedge42/setMaterial Aluminium
/gate/Awedge42/vis/setColor gray
/gate/Awedge42/placement/setTranslation 12.0964 585.105 0 mm
/gate/Awedge42/placement/setRotationAxis -1 1 0
/gate/Awedge42/placement/setRotationAngle 180 deg
/gate/world/daughters/name Awedge43
/gate/world/daughters/insert wedge
/gate/Awedge43/geometry/setNarrowerXLength 0.216017 mm
/gate/Awedge43/geometry/setXLength 0.227936 mm
/gate/Awedge43/geometry/setYLength 0.317089 mm 
/gate/Awedge43/geometry/setZLength 32 mm
/gate/Awedge43/setMaterial Aluminium
/gate/Awedge43/vis/setColor gray
/gate/Awedge43/placement/setTranslation 12.4123 585.111 0 mm
/gate/Awedge43/placement/setRotationAxis -1 1 0
/gate/Awedge43/placement/setRotationAngle 180 deg
/gate/world/daughters/name Awedge44
/gate/world/daughters/insert wedge
/gate/Awedge44/geometry/setNarrowerXLength 0.227936 mm
/gate/Awedge44/geometry/setXLength 0.240643 mm
/gate/Awedge44/geometry/setYLength 0.319601 mm 
/gate/Awedge44/geometry/setZLength 32 mm
/gate/Awedge44/setMaterial Aluminium
/gate/Awedge44/vis/setColor gray
/gate/Awedge44/placement/setTranslation 12.7307 585.117 0 mm
/gate/Awedge44/placement/setRotationAxis -1 1 0
/gate/Awedge44/placement/setRotationAngle 180 deg
/gate/world/daughters/name Awedge45
/gate/world/daughters/insert wedge
/gate/Awedge45/geometry/setNarrowerXLength 0.240643 mm
/gate/Awedge45/geometry/setXLength 0.254265 mm
/gate/Awedge45/geometry/setYLength 0.322225 mm 
/gate/Awedge45/geometry/setZLength 32 mm
/gate/Awedge45/setMaterial Aluminium
/gate/Awedge45/vis/setColor gray
/gate/Awedge45/placement/setTranslation 13.0516 585.124 0 mm
/gate/Awedge45/placement/setRotationAxis -1 1 0
/gate/Awedge45/placement/setRotationAngle 180 deg
/gate/world/daughters/name Awedge46
/gate/world/daughters/insert wedge
/gate/Awedge46/geometry/setNarrowerXLength 0.254265 mm
/gate/Awedge46/geometry/setXLength 0.26895 mm
/gate/Awedge46/geometry/setYLength 0.324972 mm 
/gate/Awedge46/geometry/setZLength 32 mm
/gate/Awedge46/setMaterial Aluminium
/gate/Awedge46/vis/setColor gray
/gate/Awedge46/placement/setTranslation 13.3752 585.131 0 mm
/gate/Awedge46/placement/setRotationAxis -1 1 0
/gate/Awedge46/placement/setRotationAngle 180 deg
/gate/world/daughters/name Awedge47
/gate/world/daughters/insert wedge
/gate/Awedge47/geometry/setNarrowerXLength 0.26895 mm
/gate/Awedge47/geometry/setXLength 0.284873 mm
/gate/Awedge47/geometry/setYLength 0.327852 mm 
/gate/Awedge47/geometry/setZLength 32 mm
/gate/Awedge47/setMaterial Aluminium
/gate/Awedge47/vis/setColor gray
/gate/Awedge47/placement/setTranslation 13.7016 585.138 0 mm
/gate/Awedge47/placement/setRotationAxis -1 1 0
/gate/Awedge47/placement/setRotationAngle 180 deg
/gate/world/daughters/name Awedge48
/gate/world/daughters/insert wedge
/gate/Awedge48/geometry/setNarrowerXLength 0.284873 mm
/gate/Awedge48/geometry/setXLength 0.302236 mm
/gate/Awedge48/geometry/setYLength 0.330877 mm 
/gate/Awedge48/geometry/setZLength 32 mm
/gate/Awedge48/setMaterial Aluminium
/gate/Awedge48/vis/setColor gray
/gate/Awedge48/placement/setTranslation 14.031 585.147 0 mm
/gate/Awedge48/placement/setRotationAxis -1 1 0
/gate/Awedge48/placement/setRotationAngle 180 deg
/gate/world/daughters/name Awedgeder
/gate/world/daughters/insert box
/gate/Awedgeder/geometry/setXLength 80 mm
/gate/Awedgeder/geometry/setYLength 0.302236 mm 
/gate/Awedgeder/geometry/setZLength 32 mm
/gate/Awedgeder/setMaterial Aluminium
/gate/Awedgeder/vis/setColor gray
/gate/Awedgeder/placement/setTranslation 54.031 585.151 0 mm
/gate/world/daughters/name Awedge49
/gate/world/daughters/insert wedge
/gate/Awedge49/geometry/setNarrowerXLength 1e-05 mm
/gate/Awedge49/geometry/setXLength 0.00439901 mm
/gate/Awedge49/geometry/setYLength 0.270533 mm 
/gate/Awedge49/geometry/setZLength 32 mm
/gate/Awedge49/setMaterial Aluminium
/gate/Awedge49/vis/setColor gray
/gate/Awedge49/placement/setTranslation -0.135267 585.001 0 mm
/gate/Awedge49/placement/setRotationAxis 0 0 1
/gate/Awedge49/placement/setRotationAngle -90 deg
/gate/world/daughters/name Awedge50
/gate/world/daughters/insert wedge
/gate/Awedge50/geometry/setNarrowerXLength 0.00439901 mm
/gate/Awedge50/geometry/setXLength 0.00879873 mm
/gate/Awedge50/geometry/setYLength 0.270578 mm 
/gate/Awedge50/geometry/setZLength 32 mm
/gate/Awedge50/setMaterial Aluminium
/gate/Awedge50/vis/setColor gray
/gate/Awedge50/placement/setTranslation -0.405822 585.003 0 mm
/gate/Awedge50/placement/setRotationAxis 0 0 1
/gate/Awedge50/placement/setRotationAngle -90 deg
/gate/world/daughters/name Awedge51
/gate/world/daughters/insert wedge
/gate/Awedge51/geometry/setNarrowerXLength 0.00879873 mm
/gate/Awedge51/geometry/setXLength 0.0131999 mm
/gate/Awedge51/geometry/setYLength 0.270666 mm 
/gate/Awedge51/geometry/setZLength 32 mm
/gate/Awedge51/setMaterial Aluminium
/gate/Awedge51/vis/setColor gray
/gate/Awedge51/placement/setTranslation -0.676444 585.005 0 mm
/gate/Awedge51/placement/setRotationAxis 0 0 1
/gate/Awedge51/placement/setRotationAngle -90 deg
/gate/world/daughters/name Awedge52
/gate/world/daughters/insert wedge
/gate/Awedge52/geometry/setNarrowerXLength 0.0131999 mm
/gate/Awedge52/geometry/setXLength 0.0176032 mm
/gate/Awedge52/geometry/setYLength 0.270799 mm 
/gate/Awedge52/geometry/setZLength 32 mm
/gate/Awedge52/setMaterial Aluminium
/gate/Awedge52/vis/setColor gray
/gate/Awedge52/placement/setTranslation -0.947176 585.008 0 mm
/gate/Awedge52/placement/setRotationAxis 0 0 1
/gate/Awedge52/placement/setRotationAngle -90 deg
/gate/world/daughters/name Awedge53
/gate/world/daughters/insert wedge
/gate/Awedge53/geometry/setNarrowerXLength 0.0176032 mm
/gate/Awedge53/geometry/setXLength 0.0220094 mm
/gate/Awedge53/geometry/setYLength 0.270976 mm 
/gate/Awedge53/geometry/setZLength 32 mm
/gate/Awedge53/setMaterial Aluminium
/gate/Awedge53/vis/setColor gray
/gate/Awedge53/placement/setTranslation -1.21806 585.01 0 mm
/gate/Awedge53/placement/setRotationAxis 0 0 1
/gate/Awedge53/placement/setRotationAngle -90 deg
/gate/world/daughters/name Awedge54
/gate/world/daughters/insert wedge
/gate/Awedge54/geometry/setNarrowerXLength 0.0220094 mm
/gate/Awedge54/geometry/setXLength 0.0264192 mm
/gate/Awedge54/geometry/setYLength 0.271197 mm 
/gate/Awedge54/geometry/setZLength 32 mm
/gate/Awedge54/setMaterial Aluminium
/gate/Awedge54/vis/setColor gray
/gate/Awedge54/placement/setTranslation -1.48915 585.012 0 mm
/gate/Awedge54/placement/setRotationAxis 0 0 1
/gate/Awedge54/placement/setRotationAngle -90 deg
/gate/world/daughters/name Awedge55
/gate/world/daughters/insert wedge
/gate/Awedge55/geometry/setNarrowerXLength 0.0264192 mm
/gate/Awedge55/geometry/setXLength 0.0308334 mm
/gate/Awedge55/geometry/setYLength 0.271463 mm 
/gate/Awedge55/geometry/setZLength 32 mm
/gate/Awedge55/setMaterial Aluminium
/gate/Awedge55/vis/setColor gray
/gate/Awedge55/placement/setTranslation -1.76048 585.014 0 mm
/gate/Awedge55/placement/setRotationAxis 0 0 1
/gate/Awedge55/placement/setRotationAngle -90 deg
/gate/world/daughters/name Awedge56
/gate/world/daughters/insert wedge
/gate/Awedge56/geometry/setNarrowerXLength 0.0308334 mm
/gate/Awedge56/geometry/setXLength 0.0352525 mm
/gate/Awedge56/geometry/setYLength 0.271774 mm 
/gate/Awedge56/geometry/setZLength 32 mm
/gate/Awedge56/setMaterial Aluminium
/gate/Awedge56/vis/setColor gray
/gate/Awedge56/placement/setTranslation -2.0321 585.017 0 mm
/gate/Awedge56/placement/setRotationAxis 0 0 1
/gate/Awedge56/placement/setRotationAngle -90 deg
/gate/world/daughters/name Awedge57
/gate/world/daughters/insert wedge
/gate/Awedge57/geometry/setNarrowerXLength 0.0352525 mm
/gate/Awedge57/geometry/setXLength 0.0396775 mm
/gate/Awedge57/geometry/setYLength 0.27213 mm 
/gate/Awedge57/geometry/setZLength 32 mm
/gate/Awedge57/setMaterial Aluminium
/gate/Awedge57/vis/setColor gray
/gate/Awedge57/placement/setTranslation -2.30405 585.019 0 mm
/gate/Awedge57/placement/setRotationAxis 0 0 1
/gate/Awedge57/placement/setRotationAngle -90 deg
/gate/world/daughters/name Awedge58
/gate/world/daughters/insert wedge
/gate/Awedge58/geometry/setNarrowerXLength 0.0396775 mm
/gate/Awedge58/geometry/setXLength 0.044109 mm
/gate/Awedge58/geometry/setYLength 0.272531 mm 
/gate/Awedge58/geometry/setZLength 32 mm
/gate/Awedge58/setMaterial Aluminium
/gate/Awedge58/vis/setColor gray
/gate/Awedge58/placement/setTranslation -2.57638 585.021 0 mm
/gate/Awedge58/placement/setRotationAxis 0 0 1
/gate/Awedge58/placement/setRotationAngle -90 deg
/gate/world/daughters/name Awedge59
/gate/world/daughters/insert wedge
/gate/Awedge59/geometry/setNarrowerXLength 0.044109 mm
/gate/Awedge59/geometry/setXLength 0.0485478 mm
/gate/Awedge59/geometry/setYLength 0.272977 mm 
/gate/Awedge59/geometry/setZLength 32 mm
/gate/Awedge59/setMaterial Aluminium
/gate/Awedge59/vis/setColor gray
/gate/Awedge59/placement/setTranslation -2.84914 585.023 0 mm
/gate/Awedge59/placement/setRotationAxis 0 0 1
/gate/Awedge59/placement/setRotationAngle -90 deg
/gate/world/daughters/name Awedge60
/gate/world/daughters/insert wedge
/gate/Awedge60/geometry/setNarrowerXLength 0.0485478 mm
/gate/Awedge60/geometry/setXLength 0.0529945 mm
/gate/Awedge60/geometry/setYLength 0.273469 mm 
/gate/Awedge60/geometry/setZLength 32 mm
/gate/Awedge60/setMaterial Aluminium
/gate/Awedge60/vis/setColor gray
/gate/Awedge60/placement/setTranslation -3.12236 585.025 0 mm
/gate/Awedge60/placement/setRotationAxis 0 0 1
/gate/Awedge60/placement/setRotationAngle -90 deg
/gate/world/daughters/name Awedge61
/gate/world/daughters/insert wedge
/gate/Awedge61/geometry/setNarrowerXLength 0.0529945 mm
/gate/Awedge61/geometry/setXLength 0.05745 mm
/gate/Awedge61/geometry/setYLength 0.274007 mm 
/gate/Awedge61/geometry/setZLength 32 mm
/gate/Awedge61/setMaterial Aluminium
/gate/Awedge61/vis/setColor gray
/gate/Awedge61/placement/setTranslation -3.3961 585.028 0 mm
/gate/Awedge61/placement/setRotationAxis 0 0 1
/gate/Awedge61/placement/setRotationAngle -90 deg
/gate/world/daughters/name Awedge62
/gate/world/daughters/insert wedge
/gate/Awedge62/geometry/setNarrowerXLength 0.05745 mm
/gate/Awedge62/geometry/setXLength 0.061915 mm
/gate/Awedge62/geometry/setYLength 0.274592 mm 
/gate/Awedge62/geometry/setZLength 32 mm
/gate/Awedge62/setMaterial Aluminium
/gate/Awedge62/vis/setColor gray
/gate/Awedge62/placement/setTranslation -3.6704 585.03 0 mm
/gate/Awedge62/placement/setRotationAxis 0 0 1
/gate/Awedge62/placement/setRotationAngle -90 deg
/gate/world/daughters/name Awedge63
/gate/world/daughters/insert wedge
/gate/Awedge63/geometry/setNarrowerXLength 0.061915 mm
/gate/Awedge63/geometry/setXLength 0.0663903 mm
/gate/Awedge63/geometry/setYLength 0.275223 mm 
/gate/Awedge63/geometry/setZLength 32 mm
/gate/Awedge63/setMaterial Aluminium
/gate/Awedge63/vis/setColor gray
/gate/Awedge63/placement/setTranslation -3.9453 585.032 0 mm
/gate/Awedge63/placement/setRotationAxis 0 0 1
/gate/Awedge63/placement/setRotationAngle -90 deg
/gate/world/daughters/name Awedge64
/gate/world/daughters/insert wedge
/gate/Awedge64/geometry/setNarrowerXLength 0.0663903 mm
/gate/Awedge64/geometry/setXLength 0.0708765 mm
/gate/Awedge64/geometry/setYLength 0.275901 mm 
/gate/Awedge64/geometry/setZLength 32 mm
/gate/Awedge64/setMaterial Aluminium
/gate/Awedge64/vis/setColor gray
/gate/Awedge64/placement/setTranslation -4.22087 585.034 0 mm
/gate/Awedge64/placement/setRotationAxis 0 0 1
/gate/Awedge64/placement/setRotationAngle -90 deg
/gate/world/daughters/name Awedge65
/gate/world/daughters/insert wedge
/gate/Awedge65/geometry/setNarrowerXLength 0.0708765 mm
/gate/Awedge65/geometry/setXLength 0.0753746 mm
/gate/Awedge65/geometry/setYLength 0.276626 mm 
/gate/Awedge65/geometry/setZLength 32 mm
/gate/Awedge65/setMaterial Aluminium
/gate/Awedge65/vis/setColor gray
/gate/Awedge65/placement/setTranslation -4.49713 585.037 0 mm
/gate/Awedge65/placement/setRotationAxis 0 0 1
/gate/Awedge65/placement/setRotationAngle -90 deg
/gate/world/daughters/name Awedge66
/gate/world/daughters/insert wedge
/gate/Awedge66/geometry/setNarrowerXLength 0.0753746 mm
/gate/Awedge66/geometry/setXLength 0.0798853 mm
/gate/Awedge66/geometry/setYLength 0.277399 mm 
/gate/Awedge66/geometry/setZLength 32 mm
/gate/Awedge66/setMaterial Aluminium
/gate/Awedge66/vis/setColor gray
/gate/Awedge66/placement/setTranslation -4.77414 585.039 0 mm
/gate/Awedge66/placement/setRotationAxis 0 0 1
/gate/Awedge66/placement/setRotationAngle -90 deg
/gate/world/daughters/name Awedge67
/gate/world/daughters/insert wedge
/gate/Awedge67/geometry/setNarrowerXLength 0.0798853 mm
/gate/Awedge67/geometry/setXLength 0.0844093 mm
/gate/Awedge67/geometry/setYLength 0.278221 mm 
/gate/Awedge67/geometry/setZLength 32 mm
/gate/Awedge67/setMaterial Aluminium
/gate/Awedge67/vis/setColor gray
/gate/Awedge67/placement/setTranslation -5.05195 585.041 0 mm
/gate/Awedge67/placement/setRotationAxis 0 0 1
/gate/Awedge67/placement/setRotationAngle -90 deg
/gate/world/daughters/name Awedge68
/gate/world/daughters/insert wedge
/gate/Awedge68/geometry/setNarrowerXLength 0.0844093 mm
/gate/Awedge68/geometry/setXLength 0.0889474 mm
/gate/Awedge68/geometry/setYLength 0.279091 mm 
/gate/Awedge68/geometry/setZLength 32 mm
/gate/Awedge68/setMaterial Aluminium
/gate/Awedge68/vis/setColor gray
/gate/Awedge68/placement/setTranslation -5.33061 585.043 0 mm
/gate/Awedge68/placement/setRotationAxis 0 0 1
/gate/Awedge68/placement/setRotationAngle -90 deg
/gate/world/daughters/name Awedge69
/gate/world/daughters/insert wedge
/gate/Awedge69/geometry/setNarrowerXLength 0.0889474 mm
/gate/Awedge69/geometry/setXLength 0.0935006 mm
/gate/Awedge69/geometry/setYLength 0.280011 mm 
/gate/Awedge69/geometry/setZLength 32 mm
/gate/Awedge69/setMaterial Aluminium
/gate/Awedge69/vis/setColor gray
/gate/Awedge69/placement/setTranslation -5.61016 585.046 0 mm
/gate/Awedge69/placement/setRotationAxis 0 0 1
/gate/Awedge69/placement/setRotationAngle -90 deg
/gate/world/daughters/name Awedge70
/gate/world/daughters/insert wedge
/gate/Awedge70/geometry/setNarrowerXLength 0.0935006 mm
/gate/Awedge70/geometry/setXLength 0.0980694 mm
/gate/Awedge70/geometry/setYLength 0.280981 mm 
/gate/Awedge70/geometry/setZLength 32 mm
/gate/Awedge70/setMaterial Aluminium
/gate/Awedge70/vis/setColor gray
/gate/Awedge70/placement/setTranslation -5.89065 585.048 0 mm
/gate/Awedge70/placement/setRotationAxis 0 0 1
/gate/Awedge70/placement/setRotationAngle -90 deg
/gate/world/daughters/name Awedge71
/gate/world/daughters/insert wedge
/gate/Awedge71/geometry/setNarrowerXLength 0.0980694 mm
/gate/Awedge71/geometry/setXLength 0.102655 mm
/gate/Awedge71/geometry/setYLength 0.282001 mm 
/gate/Awedge71/geometry/setZLength 32 mm
/gate/Awedge71/setMaterial Aluminium
/gate/Awedge71/vis/setColor gray
/gate/Awedge71/placement/setTranslation -6.17215 585.05 0 mm
/gate/Awedge71/placement/setRotationAxis 0 0 1
/gate/Awedge71/placement/setRotationAngle -90 deg
/gate/world/daughters/name Awedge72
/gate/world/daughters/insert wedge
/gate/Awedge72/geometry/setNarrowerXLength 0.102655 mm
/gate/Awedge72/geometry/setXLength 0.107258 mm
/gate/Awedge72/geometry/setYLength 0.283073 mm 
/gate/Awedge72/geometry/setZLength 32 mm
/gate/Awedge72/setMaterial Aluminium
/gate/Awedge72/vis/setColor gray
/gate/Awedge72/placement/setTranslation -6.45468 585.052 0 mm
/gate/Awedge72/placement/setRotationAxis 0 0 1
/gate/Awedge72/placement/setRotationAngle -90 deg
/gate/world/daughters/name Awedge73
/gate/world/daughters/insert wedge
/gate/Awedge73/geometry/setNarrowerXLength 0.107258 mm
/gate/Awedge73/geometry/setXLength 0.111879 mm
/gate/Awedge73/geometry/setYLength 0.284197 mm 
/gate/Awedge73/geometry/setZLength 32 mm
/gate/Awedge73/setMaterial Aluminium
/gate/Awedge73/vis/setColor gray
/gate/Awedge73/placement/setTranslation -6.73832 585.055 0 mm
/gate/Awedge73/placement/setRotationAxis 0 0 1
/gate/Awedge73/placement/setRotationAngle -90 deg
/gate/world/daughters/name Awedge74
/gate/world/daughters/insert wedge
/gate/Awedge74/geometry/setNarrowerXLength 0.111879 mm
/gate/Awedge74/geometry/setXLength 0.116519 mm
/gate/Awedge74/geometry/setYLength 0.285373 mm 
/gate/Awedge74/geometry/setZLength 32 mm
/gate/Awedge74/setMaterial Aluminium
/gate/Awedge74/vis/setColor gray
/gate/Awedge74/placement/setTranslation -7.0231 585.057 0 mm
/gate/Awedge74/placement/setRotationAxis 0 0 1
/gate/Awedge74/placement/setRotationAngle -90 deg
/gate/world/daughters/name Awedge75
/gate/world/daughters/insert wedge
/gate/Awedge75/geometry/setNarrowerXLength 0.116519 mm
/gate/Awedge75/geometry/setXLength 0.12118 mm
/gate/Awedge75/geometry/setYLength 0.286603 mm 
/gate/Awedge75/geometry/setZLength 32 mm
/gate/Awedge75/setMaterial Aluminium
/gate/Awedge75/vis/setColor gray
/gate/Awedge75/placement/setTranslation -7.30909 585.059 0 mm
/gate/Awedge75/placement/setRotationAxis 0 0 1
/gate/Awedge75/placement/setRotationAngle -90 deg
/gate/world/daughters/name Awedge76
/gate/world/daughters/insert wedge
/gate/Awedge76/geometry/setNarrowerXLength 0.12118 mm
/gate/Awedge76/geometry/setXLength 0.125861 mm
/gate/Awedge76/geometry/setYLength 0.287888 mm 
/gate/Awedge76/geometry/setZLength 32 mm
/gate/Awedge76/setMaterial Aluminium
/gate/Awedge76/vis/setColor gray
/gate/Awedge76/placement/setTranslation -7.59634 585.062 0 mm
/gate/Awedge76/placement/setRotationAxis 0 0 1
/gate/Awedge76/placement/setRotationAngle -90 deg
/gate/world/daughters/name Awedge77
/gate/world/daughters/insert wedge
/gate/Awedge77/geometry/setNarrowerXLength 0.125861 mm
/gate/Awedge77/geometry/setXLength 0.130564 mm
/gate/Awedge77/geometry/setYLength 0.289227 mm 
/gate/Awedge77/geometry/setZLength 32 mm
/gate/Awedge77/setMaterial Aluminium
/gate/Awedge77/vis/setColor gray
/gate/Awedge77/placement/setTranslation -7.88489 585.064 0 mm
/gate/Awedge77/placement/setRotationAxis 0 0 1
/gate/Awedge77/placement/setRotationAngle -90 deg
/gate/world/daughters/name Awedge78
/gate/world/daughters/insert wedge
/gate/Awedge78/geometry/setNarrowerXLength 0.130564 mm
/gate/Awedge78/geometry/setXLength 0.13529 mm
/gate/Awedge78/geometry/setYLength 0.290624 mm 
/gate/Awedge78/geometry/setZLength 32 mm
/gate/Awedge78/setMaterial Aluminium
/gate/Awedge78/vis/setColor gray
/gate/Awedge78/placement/setTranslation -8.17482 585.066 0 mm
/gate/Awedge78/placement/setRotationAxis 0 0 1
/gate/Awedge78/placement/setRotationAngle -90 deg
/gate/world/daughters/name Awedge79
/gate/world/daughters/insert wedge
/gate/Awedge79/geometry/setNarrowerXLength 0.13529 mm
/gate/Awedge79/geometry/setXLength 0.140039 mm
/gate/Awedge79/geometry/setYLength 0.292077 mm 
/gate/Awedge79/geometry/setZLength 32 mm
/gate/Awedge79/setMaterial Aluminium
/gate/Awedge79/vis/setColor gray
/gate/Awedge79/placement/setTranslation -8.46617 585.069 0 mm
/gate/Awedge79/placement/setRotationAxis 0 0 1
/gate/Awedge79/placement/setRotationAngle -90 deg
/gate/world/daughters/name Awedge80
/gate/world/daughters/insert wedge
/gate/Awedge80/geometry/setNarrowerXLength 0.140039 mm
/gate/Awedge80/geometry/setXLength 0.144813 mm
/gate/Awedge80/geometry/setYLength 0.29359 mm 
/gate/Awedge80/geometry/setZLength 32 mm
/gate/Awedge80/setMaterial Aluminium
/gate/Awedge80/vis/setColor gray
/gate/Awedge80/placement/setTranslation -8.759 585.071 0 mm
/gate/Awedge80/placement/setRotationAxis 0 0 1
/gate/Awedge80/placement/setRotationAngle -90 deg
/gate/world/daughters/name Awedge81
/gate/world/daughters/insert wedge
/gate/Awedge81/geometry/setNarrowerXLength 0.144813 mm
/gate/Awedge81/geometry/setXLength 0.149612 mm
/gate/Awedge81/geometry/setYLength 0.295163 mm 
/gate/Awedge81/geometry/setZLength 32 mm
/gate/Awedge81/setMaterial Aluminium
/gate/Awedge81/vis/setColor gray
/gate/Awedge81/placement/setTranslation -9.05338 585.074 0 mm
/gate/Awedge81/placement/setRotationAxis 0 0 1
/gate/Awedge81/placement/setRotationAngle -90 deg
/gate/world/daughters/name Awedge82
/gate/world/daughters/insert wedge
/gate/Awedge82/geometry/setNarrowerXLength 0.149612 mm
/gate/Awedge82/geometry/setXLength 0.154438 mm
/gate/Awedge82/geometry/setYLength 0.296797 mm 
/gate/Awedge82/geometry/setZLength 32 mm
/gate/Awedge82/setMaterial Aluminium
/gate/Awedge82/vis/setColor gray
/gate/Awedge82/placement/setTranslation -9.34936 585.076 0 mm
/gate/Awedge82/placement/setRotationAxis 0 0 1
/gate/Awedge82/placement/setRotationAngle -90 deg
/gate/world/daughters/name Awedge83
/gate/world/daughters/insert wedge
/gate/Awedge83/geometry/setNarrowerXLength 0.154438 mm
/gate/Awedge83/geometry/setXLength 0.159292 mm
/gate/Awedge83/geometry/setYLength 0.298495 mm 
/gate/Awedge83/geometry/setZLength 32 mm
/gate/Awedge83/setMaterial Aluminium
/gate/Awedge83/vis/setColor gray
/gate/Awedge83/placement/setTranslation -9.64701 585.078 0 mm
/gate/Awedge83/placement/setRotationAxis 0 0 1
/gate/Awedge83/placement/setRotationAngle -90 deg
/gate/world/daughters/name Awedge84
/gate/world/daughters/insert wedge
/gate/Awedge84/geometry/setNarrowerXLength 0.159292 mm
/gate/Awedge84/geometry/setXLength 0.164174 mm
/gate/Awedge84/geometry/setYLength 0.300259 mm 
/gate/Awedge84/geometry/setZLength 32 mm
/gate/Awedge84/setMaterial Aluminium
/gate/Awedge84/vis/setColor gray
/gate/Awedge84/placement/setTranslation -9.94638 585.081 0 mm
/gate/Awedge84/placement/setRotationAxis 0 0 1
/gate/Awedge84/placement/setRotationAngle -90 deg
/gate/world/daughters/name Awedge85
/gate/world/daughters/insert wedge
/gate/Awedge85/geometry/setNarrowerXLength 0.164174 mm
/gate/Awedge85/geometry/setXLength 0.169086 mm
/gate/Awedge85/geometry/setYLength 0.30209 mm 
/gate/Awedge85/geometry/setZLength 32 mm
/gate/Awedge85/setMaterial Aluminium
/gate/Awedge85/vis/setColor gray
/gate/Awedge85/placement/setTranslation -10.2476 585.083 0 mm
/gate/Awedge85/placement/setRotationAxis 0 0 1
/gate/Awedge85/placement/setRotationAngle -90 deg
/gate/world/daughters/name Awedge86
/gate/world/daughters/insert wedge
/gate/Awedge86/geometry/setNarrowerXLength 0.169086 mm
/gate/Awedge86/geometry/setXLength 0.17403 mm
/gate/Awedge86/geometry/setYLength 0.303992 mm 
/gate/Awedge86/geometry/setZLength 32 mm
/gate/Awedge86/setMaterial Aluminium
/gate/Awedge86/vis/setColor gray
/gate/Awedge86/placement/setTranslation -10.5506 585.086 0 mm
/gate/Awedge86/placement/setRotationAxis 0 0 1
/gate/Awedge86/placement/setRotationAngle -90 deg
/gate/world/daughters/name Awedge87
/gate/world/daughters/insert wedge
/gate/Awedge87/geometry/setNarrowerXLength 0.17403 mm
/gate/Awedge87/geometry/setXLength 0.179005 mm
/gate/Awedge87/geometry/setYLength 0.305968 mm 
/gate/Awedge87/geometry/setZLength 32 mm
/gate/Awedge87/setMaterial Aluminium
/gate/Awedge87/vis/setColor gray
/gate/Awedge87/placement/setTranslation -10.8556 585.088 0 mm
/gate/Awedge87/placement/setRotationAxis 0 0 1
/gate/Awedge87/placement/setRotationAngle -90 deg
/gate/world/daughters/name Awedge88
/gate/world/daughters/insert wedge
/gate/Awedge88/geometry/setNarrowerXLength 0.179005 mm
/gate/Awedge88/geometry/setXLength 0.184013 mm
/gate/Awedge88/geometry/setYLength 0.30802 mm 
/gate/Awedge88/geometry/setZLength 32 mm
/gate/Awedge88/setMaterial Aluminium
/gate/Awedge88/vis/setColor gray
/gate/Awedge88/placement/setTranslation -11.1626 585.091 0 mm
/gate/Awedge88/placement/setRotationAxis 0 0 1
/gate/Awedge88/placement/setRotationAngle -90 deg
/gate/world/daughters/name Awedge89
/gate/world/daughters/insert wedge
/gate/Awedge89/geometry/setNarrowerXLength 0.184013 mm
/gate/Awedge89/geometry/setXLength 0.194137 mm
/gate/Awedge89/geometry/setYLength 0.310153 mm 
/gate/Awedge89/geometry/setZLength 32 mm
/gate/Awedge89/setMaterial Aluminium
/gate/Awedge89/vis/setColor gray
/gate/Awedge89/placement/setTranslation -11.4717 585.095 0 mm
/gate/Awedge89/placement/setRotationAxis 0 0 1
/gate/Awedge89/placement/setRotationAngle -90 deg
/gate/world/daughters/name Awedge90
/gate/world/daughters/insert wedge
/gate/Awedge90/geometry/setNarrowerXLength 0.194137 mm
/gate/Awedge90/geometry/setXLength 0.204781 mm
/gate/Awedge90/geometry/setYLength 0.312372 mm 
/gate/Awedge90/geometry/setZLength 32 mm
/gate/Awedge90/setMaterial Aluminium
/gate/Awedge90/vis/setColor gray
/gate/Awedge90/placement/setTranslation -11.7829 585.1 0 mm
/gate/Awedge90/placement/setRotationAxis 0 0 1
/gate/Awedge90/placement/setRotationAngle -90 deg
/gate/world/daughters/name Awedge91
/gate/world/daughters/insert wedge
/gate/Awedge91/geometry/setNarrowerXLength 0.204781 mm
/gate/Awedge91/geometry/setXLength 0.216017 mm
/gate/Awedge91/geometry/setYLength 0.314682 mm 
/gate/Awedge91/geometry/setZLength 32 mm
/gate/Awedge91/setMaterial Aluminium
/gate/Awedge91/vis/setColor gray
/gate/Awedge91/placement/setTranslation -12.0964 585.105 0 mm
/gate/Awedge91/placement/setRotationAxis 0 0 1
/gate/Awedge91/placement/setRotationAngle -90 deg
/gate/world/daughters/name Awedge92
/gate/world/daughters/insert wedge
/gate/Awedge92/geometry/setNarrowerXLength 0.216017 mm
/gate/Awedge92/geometry/setXLength 0.227936 mm
/gate/Awedge92/geometry/setYLength 0.317089 mm 
/gate/Awedge92/geometry/setZLength 32 mm
/gate/Awedge92/setMaterial Aluminium
/gate/Awedge92/vis/setColor gray
/gate/Awedge92/placement/setTranslation -12.4123 585.111 0 mm
/gate/Awedge92/placement/setRotationAxis 0 0 1
/gate/Awedge92/placement/setRotationAngle -90 deg
/gate/world/daughters/name Awedge93
/gate/world/daughters/insert wedge
/gate/Awedge93/geometry/setNarrowerXLength 0.227936 mm
/gate/Awedge93/geometry/setXLength 0.240643 mm
/gate/Awedge93/geometry/setYLength 0.319601 mm 
/gate/Awedge93/geometry/setZLength 32 mm
/gate/Awedge93/setMaterial Aluminium
/gate/Awedge93/vis/setColor gray
/gate/Awedge93/placement/setTranslation -12.7307 585.117 0 mm
/gate/Awedge93/placement/setRotationAxis 0 0 1
/gate/Awedge93/placement/setRotationAngle -90 deg
/gate/world/daughters/name Awedge94
/gate/world/daughters/insert wedge
/gate/Awedge94/geometry/setNarrowerXLength 0.240643 mm
/gate/Awedge94/geometry/setXLength 0.254265 mm
/gate/Awedge94/geometry/setYLength 0.322225 mm 
/gate/Awedge94/geometry/setZLength 32 mm
/gate/Awedge94/setMaterial Aluminium
/gate/Awedge94/vis/setColor gray
/gate/Awedge94/placement/setTranslation -13.0516 585.124 0 mm
/gate/Awedge94/placement/setRotationAxis 0 0 1
/gate/Awedge94/placement/setRotationAngle -90 deg
/gate/world/daughters/name Awedge95
/gate/world/daughters/insert wedge
/gate/Awedge95/geometry/setNarrowerXLength 0.254265 mm
/gate/Awedge95/geometry/setXLength 0.26895 mm
/gate/Awedge95/geometry/setYLength 0.324972 mm 
/gate/Awedge95/geometry/setZLength 32 mm
/gate/Awedge95/setMaterial Aluminium
/gate/Awedge95/vis/setColor gray
/gate/Awedge95/placement/setTranslation -13.3752 585.131 0 mm
/gate/Awedge95/placement/setRotationAxis 0 0 1
/gate/Awedge95/placement/setRotationAngle -90 deg
/gate/world/daughters/name Awedge96
/gate/world/daughters/insert wedge
/gate/Awedge96/geometry/setNarrowerXLength 0.26895 mm
/gate/Awedge96/geometry/setXLength 0.284873 mm
/gate/Awedge96/geometry/setYLength 0.327852 mm 
/gate/Awedge96/geometry/setZLength 32 mm
/gate/Awedge96/setMaterial Aluminium
/gate/Awedge96/vis/setColor gray
/gate/Awedge96/placement/setTranslation -13.7016 585.138 0 mm
/gate/Awedge96/placement/setRotationAxis 0 0 1
/gate/Awedge96/placement/setRotationAngle -90 deg
/gate/world/daughters/name Awedge97
/gate/world/daughters/insert wedge
/gate/Awedge97/geometry/setNarrowerXLength 0.284873 mm
/gate/Awedge97/geometry/setXLength 0.302236 mm
/gate/Awedge97/geometry/setYLength 0.330877 mm 
/gate/Awedge97/geometry/setZLength 32 mm
/gate/Awedge97/setMaterial Aluminium
/gate/Awedge97/vis/setColor gray
/gate/Awedge97/placement/setTranslation -14.031 585.147 0 mm
/gate/Awedge97/placement/setRotationAxis 0 0 1
/gate/Awedge97/placement/setRotationAngle -90 deg
/gate/world/daughters/name Awedgeizq
/gate/world/daughters/insert box
/gate/Awedgeizq/geometry/setXLength 80 mm
/gate/Awedgeizq/geometry/setYLength 0.302236 mm 
/gate/Awedgeizq/geometry/setZLength 32 mm
/gate/Awedgeizq/setMaterial Aluminium
/gate/Awedgeizq/vis/setColor gray
/gate/Awedgeizq/placement/setTranslation -54.031 585.151 0 mm
